### ISSUE TITLE
[Bug] Module imports fail with @storybook/angular 6.3.0

### ISSUE THREAD

**Issue by Granipouss** [storybookjs/addon-angular-ivy#11]
### Describe the bug

Module imports fail with `@storybook/angular` 6.3.0-alpha and more.

### Steps to reproduce the behavior

1. Upgrade in `package.json` to `"@storybook/angular": "^6.3.0-alpha"`.
2. Create use asyncPipe in the button

```ts
import { Component, NgModule, ViewChild } from "@angular/core";
import { CommonModule } from "@angular/common";
import { of } from "rxjs";

@Component({
  selector: "sb-button",
  template: ` <button>click me {{ value$ | async }}!</button> `,
  styles: [],
})
export class ButtonComponent {
  value$ = of("Value");
}

@NgModule({
  imports: [CommonModule],
  declarations: [ButtonComponent],
  exports: [ButtonComponent],
})
export class ButtonModule {}
```

### Expected behavior

I should work.

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/19293395/120508068-afc89b00-c3c7-11eb-8bbd-26aa95c02185.png)

### Environment

 - OS: Windows
 - Node.js version: 12.21.0
 - NPM version: 6.14.11
 - Browser (if applicable): Chrome
 - Browser version (if applicable): 91.0.4472.77
 - Device (if applicable): Windows 10

### Additional context

As Storybook 6.3 is not out yet, I get that this may not be top priority. I will try to revert back on more stable versions for my project.

**Comment by kroeder** [comment]
Can you please give the latest 6.3.0 beta a try? Lots of issues have been fixed during the last couple of days

**Comment by Granipouss** [comment]
Could not reproduce it with "@storybook/angular" version 6.3.0-beta.17.

Thank you
